[package]
name = "typerip"
version = "0.1.0"
edition = "2021"

[dependencies]
ureq = "2.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
woff2-patched = "0.3.0"
clap = "2.33.3"
arboard = "3.2.0"
